name: fire
description: >
  Hot-Restart for Dart console application with fast incremental compilation.
version: 1.3.1
repository: https://github.com/ykmnkmi/fire.dart

executables:
  fire: fire

environment:
  sdk: ">=3.0.0 <4.0.0"

platforms:
  linux:
  macos:
  windows:

topics:
  - cli

dependencies:
  args: ^2.4.2
  async: ^2.11.0
  frontend_server_client: ^3.2.0
  package_config: ^2.1.0
  path: ^1.8.3
  radix_tree: ^2.0.1
  stream_transform: ^2.1.0
  watcher: ^1.1.0

dev_dependencies:
  lints: ^2.0.0
