name: fire
description: >
  Hot-Restart for Dart console application with fast incremental compilation.
version: 1.3.0-dev.5
repository: https://github.com/ykmnkmi/fire.dart

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  args: ^2.3.0
  async: ^2.10.0
  frontend_server_client: ^3.1.0
  package_config: ^2.1.0
  path: ^1.8.0
  watcher: ^1.0.0

dev_dependencies:
  lints: ^2.0.0

executables:
  fire: fire
