name: fire
description: >
  Hot-Restart for Dart console application with fast incremental compilation.
version: 1.3.0-dev.8
repository: https://github.com/ykmnkmi/fire.dart

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  args: ^2.3.1
  async: ^2.10.0
  frontend_server_client: ^3.2.0
  package_config: ^2.1.0
  path: ^1.8.2
  stream_transform: ^2.1.0
  watcher: ^1.0.2

dev_dependencies:
  lints: ^2.0.1

executables:
  fire: fire
